data <- read.table("~/AVL-vs-ABB/amostra.txt", header=T)
options(scipen=5)
maxY <- max(data$list, data$bst)
maxX <- max(data$size)
minX <- min(data$size)
minY <- min(data$list, data$bst)
plot(data$AVL~data$size, col="blue", xlab="Size", ylab="Comparisons", xlim=c(minX, maxX), ylim=c(minY, maxY))
points(data$AVL~data$size, col="red")
title(main = "AVL vs ABB")
legend("topleft", c("AVL","ABB"), col=c("blue","red"), pch=1:1, inset = c(0.05, 0.05)) 