data <- read.table("amostra.txt", header=T)
options(scipen=5)
maxY <- max(data$ABB, data$AVL)
maxX <- max(data$Size)
minX <- min(data$Size)
minY <- min(data$ABB, data$AVL)
plot(data$AVL~data$Size, col="blue", xlab="Size", ylab="Comparisons", xlim=c(minX, maxX), ylim=c(minY, maxY))
points(data$AVL~data$Size, col="red")
title(main = "AVL vs ABB")
legend("topleft", c("AVL","ABB"), col=c("blue","red"), pch=1:1, inset = c(0.05, 0.05)) 