data <- read.table("~/AVL-vs-ABB/amostra.txt", header=T)
options(scipen=5)
maxY <- max(data$AVL)
maxX <- max(data$size)
minX <- min(data$size)
minY <- min(data$AVL)
plot(data$AVL~data$size, col="blue", xlab="Size", ylab="Comparisons", xlim=c(minX, maxX), ylim=c(minY, maxY))
title(main = "Lista")
legend("topleft", c("AVL"), col=c("blue"), pch=1, inset = c(0.05, 0.05)) 
